/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.timeseriesclustering;

import java.io.File;
import javax.swing.tree.DefaultTreeModel;
import smile.data.AttributeDataset;
import smile.data.NominalAttribute;
import smile.data.parser.DelimitedTextParser;

/**
 *
 * @author surendra
 */
public class ODACMainFrame extends javax.swing.JFrame {

//    public static String msg = "";
//    public static String distancemsg = "";
    ODAClustering odac = null;
    IncrementalDissimilarityLinkage linkage = null;

    /**
     * Creates new form ODACMainFrame
     */
    public ODACMainFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jB_Run = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Online Divisive - Agglomerative Clustering For Time Series Data");
        setPreferredSize(new java.awt.Dimension(1000, 650));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 183, 1000, 470));

        jB_Run.setText("Run");
        jB_Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_RunActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_Run, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_Run, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 1000, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_RunActionPerformed
        // TODO add your handling code here:

        String msg = "";

        try {

            DelimitedTextParser parser = new DelimitedTextParser();
            parser.setRowNames(false);
            parser.setResponseIndex(new NominalAttribute("Sensor"), -1);
            AttributeDataset train = parser.parse("./data/SensorReadings_init.txt");
            double[][] x = train.toArray(new double[train.size()][]);
            msg += "Reading initial readings from ./data/SensorReadings_init.txt\n";

            int n = x.length;
            double[][] proximity = new double[n][];
            for (int i = 0; i < n; i++) {
                proximity[i] = new double[i + 1];
                for (int k = 0; k < i; k++) {
                    proximity[i][k] = IncrementalDissimilarityLinkage.calculateDistance(x[i], x[k]);
                }
            }
            linkage = new IncrementalDissimilarityLinkage(proximity);
            odac = new ODAClustering(x);

            DefaultTreeModel dm = odac.getTree();
            this.jTabbedPane1.add(new JPClusterDetails(dm, x), "Time: 0");

        } catch (Exception ex) {
            ex.printStackTrace();
        }

        // Start clustering new data
        File classDir = new File("./data", "readings");
        if (!classDir.isDirectory()) {
            String msgs = "The input is not a directory";
            System.out.println(msgs); // in case exception gets lost in shell
            throw new IllegalArgumentException(msgs);
        }

        String[] trainingFiles = classDir.list();

        for (int j = 1; j <= trainingFiles.length; ++j) {
            DelimitedTextParser parser = new DelimitedTextParser();
            parser.setRowNames(false);
            parser.setResponseIndex(new NominalAttribute("Sensor"), -1);

            try {

                AttributeDataset train = parser.parse("./data/readings/SensorReadings_" + j + ".txt");
                double[][] x = train.toArray(new double[train.size()][]);

                msg += "Reading readings from ./data/SensorReadings_" + j + ".txt at time interval " + j + "\n";

                odac.updateClusterData(x);
                DefaultTreeModel dm = odac.getTree();
                this.jTabbedPane1.add(new JPClusterDetails(dm, x), "Time: " + j);

            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }
        this.jTextArea1.setText(msg);
        odac.printTree();
        
        this.jB_Run.setEnabled(false);

    }//GEN-LAST:event_jB_RunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ODACMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ODACMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ODACMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ODACMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ODACMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Run;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
