/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.timeseriesclustering;

import java.util.List;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author rohit
 */
public class JPClusterDetails extends javax.swing.JPanel {

    /**
     * Creates new form JPClusterDetails
     */
    double[][] readings;

    public JPClusterDetails(DefaultTreeModel dm, double[][] x) {
        initComponents();
        readings = x;
        displayReadings();
        displayProximity();
        plotDendogram(dm);
    }

    private void displayReadings() {
        String msg = "";
        for (int i = 0; i < readings.length; i++) {
            msg += "X" + i + ": [  ";
            for (int j = 0; j < readings[i].length; j++) {
                msg +=  String.format("%.2f", readings[i][j]) + "  ";
            }
            msg += "]\n";
        }

        jTextArea_Readings.setText(msg);
    }

    private void displayProximity() {
        String msg="";
        int n = readings.length;
        double[][] proximity = new double[n][];
        
        for (int i = 0; i < n; i++) {
            proximity[i] = new double[i + 1];
            for (int k = 0; k < i; k++) {
                proximity[i][k] = IncrementalDissimilarityLinkage.calculateDistance(readings[i], readings[k]);
                msg+=String.format("%.3f", proximity[i][k])+"  ";
            }
            msg+="\n";
        }
        
        jTextArea_Proximity.setText(msg);
    }

    private void plotDendogram(DefaultTreeModel dm) {
        this.jTree_Dendogram.setModel(dm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Readings = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree_Dendogram = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_Proximity = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 450));

        jTextArea_Readings.setColumns(20);
        jTextArea_Readings.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Readings);

        jTree_Dendogram.setAutoscrolls(true);
        jScrollPane2.setViewportView(jTree_Dendogram);

        jTextArea_Proximity.setColumns(20);
        jTextArea_Proximity.setRows(5);
        jScrollPane3.setViewportView(jTextArea_Proximity);

        jLabel1.setText("Readings:");

        jLabel2.setText("Proximity:");

        jLabel3.setText("Cluster Tree:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea_Proximity;
    private javax.swing.JTextArea jTextArea_Readings;
    private javax.swing.JTree jTree_Dendogram;
    // End of variables declaration//GEN-END:variables

}
